# Generated by Django 4.2.14 on 2024-07-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('language', models.CharField(max_length=2)),
            ],
        ),
    ]
