# Generated by Django 4.2.14 on 2024-08-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tasks',
        ),
    ]
