# Generated by Django 4.2.14 on 2024-08-02 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_last_time_online_profile_register_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='register_date',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_time_online',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 14, 43, 55, 988028)),
        ),
    ]
