# Generated by Django 4.2.14 on 2024-08-02 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_profile_number_of_referrals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='number_of_referrals',
            new_name='number_of_friends',
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 20, 24, 41, 368625)),
        ),
    ]
