# Generated by Django 4.2.14 on 2024-08-02 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_profile_last_daily_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 20, 34, 10, 72377)),
        ),
    ]
