# Generated by Django 4.2.14 on 2024-08-04 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_profile_passive_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_learning_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='studio_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 19, 9, 27, 851890)),
        ),
    ]
