# Generated by Django 4.2.14 on 2024-08-06 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_profile_is_learning_complete_profile_studio_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profit_ratio',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 18, 46, 53, 143473)),
        ),
    ]
