# Generated by Django 4.2.14 on 2024-08-06 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_profile_profit_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 18, 47, 39, 599172)),
        ),
    ]
