# Generated by Django 4.2.14 on 2024-08-10 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_profile_next_create_available_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='next_create_available_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 11, 53, 53, 665105)),
        ),
    ]
