# Generated by Django 4.2.14 on 2024-08-11 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_remove_profile_next_create_available_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ref_code',
            new_name='referral_code',
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 19, 25, 12, 946176)),
        ),
    ]
