# Generated by Django 4.2.14 on 2024-08-11 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_profile_last_daily_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ton_wallet',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 22, 26, 40, 469604)),
        ),
    ]
