# Generated by Django 4.2.14 on 2024-08-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_comment_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
