version: '3.9'

services:
  webapp:
    build: .
    stdin_open: true 
    tty: true 
    command: bash entrypoint.sh
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    env_file:
      - file.env
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always

  db:
    image: mysql
    env_file:
      - file.env
    restart: always