services:
  webapp:
    build: .
    stdin_open: true 
    tty: true 
    volumes:
      - ./aniton:/app
      - ./aniton/static:/app/static
      - ./aniton/media:/app/media
    command: bash entrypoint.sh
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    env_file:
      - file.env
    restart: always
    networks:
      - dev

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - dev
  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - file.env
    restart: always
    networks:
      - dev
  nginx:
    build: ./nginx
    container_name: aniton_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static:/static
      - ./media:/media
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - webapp
    networks:
      - dev
  certbot:
    image: certbot/certbot:latest
#    command: certonly --webroot -w /var/www/certbot -d aniton.xyz --email cool.drakon@gmail.com --agree-tos --non-interactive --force-renewal
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw

volumes:
  mysql_data:

networks:
  dev:
