# Generated by Django 4.2.14 on 2024-08-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_cost', models.IntegerField()),
                ('influence_cost', models.IntegerField()),
            ],
        ),
    ]
