# Generated by Django 4.2.14 on 2024-08-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='cost_multiplier',
            field=models.FloatField(default=1.05),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='max_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='passive_income_boost',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upgrade',
            name='profit_ratio_boost',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='influence_cost',
            field=models.IntegerField(default=0),
        ),
    ]
