# Generated by Django 4.2.14 on 2024-08-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0002_upgrade_cost_multiplier_upgrade_max_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='name_eng',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='name_rus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='money_cost',
            field=models.IntegerField(default=0),
        ),
    ]
