# Generated by Django 4.2.14 on 2024-08-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0003_upgrade_name_eng_upgrade_name_rus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgrade',
            name='cost_multiplier',
        ),
        migrations.RemoveField(
            model_name='upgrade',
            name='max_level',
        ),
    ]
