# Generated by Django 4.2.14 on 2024-10-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0004_remove_upgrade_cost_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
