# Generated by Django 4.2.14 on 2024-11-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0005_upgrade_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='image',
            field=models.ImageField(blank=True, upload_to='upgrades/'),
        ),
    ]
