# Generated by Django 4.2.14 on 2024-08-01 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'User Tasks', 'verbose_name_plural': 'User Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 15, 45, 27, 205314)),
        ),
    ]
