# Generated by Django 4.2.14 on 2024-08-01 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_options_alter_task_last_daily_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasks',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 15, 49, 43, 297456)),
        ),
    ]
