# Generated by Django 4.2.14 on 2024-08-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='task',
            name='title_eng',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title_rus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('game', 'Game'), ('meta', 'Meta')], max_length=30),
        ),
    ]
