# Generated by Django 4.2.14 on 2024-08-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_image_task_title_eng_task_title_rus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
