# Generated by Django 4.2.14 on 2024-08-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='referrals_required',
            new_name='friends_required',
        ),
    ]
