# Generated by Django 4.2.14 on 2024-10-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_rename_referrals_required_task_friends_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
    ]
