# Generated by Django 4.2.14 on 2024-07-31 20:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_profile_influence_profile_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_streak', models.IntegerField(default=1)),
                ('last_daily_collect', models.DateTimeField(default=datetime.datetime(2024, 7, 31, 23, 45, 27, 684292))),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
