# Generated by Django 4.2.14 on 2024-08-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_tasks_alter_task_last_daily_collect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
