# Generated by Django 4.2.14 on 2024-08-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0004_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('META', 'Метовые'), ('Game', 'Игровые')], max_length=30)),
                ('is_verif_necessary', models.BooleanField(default=True)),
                ('money_required', models.IntegerField(default=0)),
                ('influence_required', models.IntegerField(default=0)),
                ('referrals_required', models.IntegerField(default=0)),
                ('daily_streak_required', models.IntegerField(default=0)),
                ('money_reward', models.IntegerField()),
                ('influence_reward', models.IntegerField()),
            ],
        ),
    ]
