# Generated by Django 4.2.14 on 2024-08-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('game', 'Game'), ('meta', 'Meta    ')], max_length=30),
        ),
    ]
