# Generated by Django 4.2.14 on 2024-11-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_remove_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, upload_to='tasks/'),
        ),
    ]
