# Generated by Django 4.2.14 on 2024-11-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
