# Generated by Django 4.2.14 on 2024-08-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rating', models.FloatField(default=0.1)),
                ('max_rating', models.FloatField(default=10.0)),
                ('text_eng', models.TextField()),
                ('text_rus', models.TextField()),
            ],
        ),
    ]
