# Generated by Django 4.2.14 on 2024-08-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Reviews',
        ),
    ]
