# Generated by Django 4.2.14 on 2024-08-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_reviews_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['min_rating', 'max_rating']},
        ),
    ]
