# Generated by Django 4.2.14 on 2024-07-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='influence',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.BigIntegerField(default=0),
        ),
    ]
