# Generated by Django 4.2.14 on 2024-08-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_influence_profile_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tasks',
            field=models.JSONField(default={}),
        ),
    ]
