# Generated by Django 4.2.14 on 2024-08-02 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_streak',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 13, 14, 51, 584667)),
        ),
        migrations.AddField(
            model_name='profile',
            name='tasks',
            field=models.JSONField(default=dict),
        ),
    ]
