# Generated by Django 4.2.14 on 2024-08-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_daily_streak_profile_last_daily_collect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_daily_collect',
        ),
        migrations.AlterField(
            model_name='profile',
            name='tasks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
