# Generated by Django 4.2.14 on 2024-08-02 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profile_last_daily_collect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 13, 44, 12, 155528)),
        ),
    ]
