# Generated by Django 4.2.14 on 2024-08-02 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_register_date_profile_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 15, 0, 58, 845609)),
        ),
    ]
