# Generated by Django 4.2.14 on 2024-08-02 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_profile_last_daily_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 16, 38, 26, 102978)),
        ),
    ]
