# Generated by Django 4.2.14 on 2024-08-02 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_number_of_referrals_profile_number_of_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upgrades',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 20, 28, 7, 100301)),
        ),
    ]
