# Generated by Django 4.2.14 on 2024-08-03 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_profile_last_daily_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ref_code',
            field=models.CharField(default='2jt04r1', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 15, 42, 9, 858358)),
        ),
    ]
