# Generated by Django 4.2.14 on 2024-08-04 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_profile_ref_code_alter_profile_last_daily_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passive_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 18, 56, 32, 799913)),
        ),
    ]
