# Generated by Django 4.2.14 on 2024-08-06 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_profile_last_daily_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 18, 50, 4, 652297)),
        ),
    ]
