# Generated by Django 4.2.14 on 2024-08-08 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_profile_last_daily_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='next_create_available_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 18, 25, 34, 889410)),
        ),
        migrations.AddField(
            model_name='profile',
            name='timeout_after_creating',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 18, 25, 34, 889364)),
        ),
    ]
