# Generated by Django 4.2.14 on 2024-08-11 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_rename_ref_code_profile_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 19, 25, 51, 213265)),
        ),
    ]
