# Generated by Django 4.2.14 on 2024-10-27 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_profile_ton_wallet_alter_profile_last_daily_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 19, 31, 11, 853671)),
        ),
    ]
