# Generated by Django 4.2.14 on 2024-10-29 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_alter_profile_last_daily_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_daily_collect',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profit_ratio',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timeout_after_creating',
            field=models.IntegerField(default=30),
        ),
    ]
