# Generated by Django 4.2.14 on 2025-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_alter_profile_last_daily_collect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timeout_after_creating',
            field=models.IntegerField(default=1),
        ),
    ]
