# Generated by Django 4.2.14 on 2025-08-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_alter_profile_timeout_after_creating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timeout_after_creating',
            field=models.IntegerField(default=30),
        ),
    ]
